development:
  adapter: postgresql
  encoding: unicode
  database: essay_101
  pool: 5



test:
  adapter: postgresql
  encoding: unicode
  database: essay_101
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: essay_101
  pool: 10